-- CreateTable
CREATE TABLE "Tarea" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "titulo" TEXT NOT NULL,
    "descripcion" TEXT NOT NULL DEFAULT '',
    "completada" BOOLEAN NOT NULL DEFAULT false,
    "creado" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
