# Verifica automaticamente que el codigo siga funcionando correctamente cada vez que se sube un cambio.
name: Node.js CI

on:
  push:
    branches:
      - main

jobs:

  auth-service:
    #Crea una máquina virtual con Ubuntu
    runs-on: ubuntu-latest

    # Todos los comandos se ejecutan sin necesidad de entrar a la carpeta
    defaults:
      run:
        working-directory: auth-service

    # Variables de entorno para GitHub Actions
    env:
      DATABASE_URL: "file:../dev.db"
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm install

      - name: Generar cliente de Prisma
        run: npx prisma generate

      - name: Ejecutar ESLint
        run: npm run lint

      - name: Ejecutar Prettier (check)
        run: npm run format:check

      - name: Ejecutar Tests
        run: npm test

  tasks-service:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tasks-service

    env:
      DATABASE_URL: "file:../dev.db"
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm install

      - name: Generar cliente de Prisma
        run: npx prisma generate

      - name: Ejecutar ESLint
        run: npm run lint

      - name: Ejecutar Prettier (check)
        run: npm run format:check

      - name: Ejecutar Tests
        run: npm test