# Verifica automaticamente que el codigo siga funcionando correctamente cada vez que se sube un cambio.
name: Node.js CI #Integracion continua

on:
  push:
    branches:
      - main

jobs:
  test:

    #Crea una máquina virtual con Ubuntu
    runs-on: ubuntu-latest

    # Variables de entorno para GitHub Actions
    env:
      DATABASE_URL: "file:./dev.db"
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25

      - name: Instalar dependencias
        run: npm install

      - name: Generar cliente de Prisma
        run: npx prisma generate

      - name: Ejecutar ESLint
        run: npm run lint

      - name: Ejecutar Tests
        run: npm test